import { useState } from 'react'
import { Link } from 'react-router-dom'
import { motion, Reorder } from 'framer-motion'
import {
  MapPin, Clock, Wallet, Users, Motorcycle, Car, PersonSimpleWalk, CheckCircle, Ruler, Sparkle, CaretDown, Bed, Star, ArrowSquareOut,
  DotsSixVertical, ArrowsClockwise, X,
} from '@phosphor-icons/react'
import { getPlace, TRANSPORT } from '../../data/destinations.js'
import { priceRangeLabel } from '../../lib/pricing.js'
import { PRICE_LEVEL_LABEL, hotelMapsUrl } from '../../lib/hotelSearch.js'
import { applyReorder, replaceStopPlace, getReplacementCandidates, usedPlaceIdsIn, recomputeDistances } from '../../lib/itineraryEdit.js'
import { useLanguage } from '../../i18n/LanguageContext.jsx'
import { fadeUp, staggerContainer } from '../../motion/variants.js'

const TRANSPORT_ICON = { bike: Motorcycle, car: Car, walk: PersonSimpleWalk, taxi: Car }

function formatVnd(n) {
  return n.toLocaleString('vi-VN') + 'đ'
}

const LABELS = {
  vi: {
    by: 'Do FoodTrip AI tạo', day: (n) => `Ngày ${n}`, perPerson: '/người', destination: 'Điểm đến', duration: 'Thời gian', people: 'Số người', transport: 'Phương tiện', budget: 'Ngân sách', open: (t) => `Mở đến ${t}`, estTotal: 'Tổng chi phí ước tính',
    address: 'Địa chỉ', viewOnMaps: 'Xem trên Google Maps (có thể có menu quán)',
    hotelsTitle: 'Khách sạn gần lịch trình của bạn', hotelReviews: (n) => `${n} đánh giá`, bookRoom: 'Đặt phòng', hotelSelected: 'Bạn đã chọn',
    dragHandle: 'Kéo để đổi thứ tự', replaceStop: 'Đổi địa điểm khác',
    replacingTitle: 'Chọn địa điểm thay thế', noCandidates: 'Không còn địa điểm nào khác cùng loại để thay.', replacing: 'Đang cập nhật…',
    choose: 'Chọn', cancel: 'Huỷ',
  },
  en: {
    by: 'Generated by FoodTrip AI', day: (n) => `Day ${n}`, perPerson: '/person', destination: 'Destination', duration: 'Duration', people: 'People', transport: 'Transport', budget: 'Budget', open: (t) => `Open until ${t}`, estTotal: 'Estimated total cost',
    address: 'Address', viewOnMaps: 'View on Google Maps (may include the menu)',
    hotelsTitle: 'Hotels near your trip', hotelReviews: (n) => `${n} reviews`, bookRoom: 'Book a room', hotelSelected: 'Your pick',
    dragHandle: 'Drag to reorder', replaceStop: 'Swap for another place',
    replacingTitle: 'Choose a replacement', noCandidates: 'No other places of this type left to swap in.', replacing: 'Updating…',
    choose: 'Choose', cancel: 'Cancel',
  },
}

function mapsSearchUrl(place, lang) {
  const query = `${place.name[lang]}, ${place.address[lang]}`
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`
}

export default function ItineraryTicket({
  city, days, hotels = [], selectedHotelId = null, people, budget, transport, animate = 'view', preferredTags = [],
  editable = false, onDaysChange, candidatePlaces = [], cityId = null,
}) {
  const { lang } = useLanguage()
  const l = LABELS[lang]
  const TransportIcon = TRANSPORT_ICON[transport] ?? Motorcycle
  const [expandedKey, setExpandedKey] = useState(null)
  const [replacingKey, setReplacingKey] = useState(null)
  const [replaceStatus, setReplaceStatus] = useState('idle') // idle | replacing
  const viewportProps =
    animate === 'view' ? { whileInView: 'show', viewport: { once: true, amount: 0.15 } } : { animate: 'show' }

  function handleReorder(dayIdx, newOrderStops) {
    const updated = applyReorder(days[dayIdx], newOrderStops, transport)
    const nextDays = days.map((d, i) => (i === dayIdx ? updated : d))
    onDaysChange?.(nextDays)
  }

  async function handleReplace(dayIdx, stopIdx, newPlace) {
    setReplaceStatus('replacing')
    const stop = days[dayIdx][stopIdx]
    const updatedStop = await replaceStopPlace(stop, newPlace, cityId)
    const updatedDay = recomputeDistances(
      days[dayIdx].map((s, i) => (i === stopIdx ? updatedStop : s)),
      transport
    )
    const nextDays = days.map((d, i) => (i === dayIdx ? updatedDay : d))
    onDaysChange?.(nextDays)
    setReplaceStatus('idle')
    setReplacingKey(null)
  }

  const durationLabel =
    days.length === 1
      ? (lang === 'vi' ? '1 ngày' : '1 day')
      : (lang === 'vi' ? `${days.length} ngày ${days.length - 1} đêm` : `${days.length}D${days.length - 1}N`)

  function StopRow({ stop, dayIdx, i }) {
    const place = getPlace(stop.placeId)
    if (!place) return null
    const matched = preferredTags.length > 0 && place.tags.some((t) => preferredTags.includes(t))
    const key = `${dayIdx}-${i}`
    const isOpen = expandedKey === key
    const isReplacing = replacingKey === key
    const candidates = isReplacing
      ? getReplacementCandidates({ candidatePlaces, category: place.category, usedPlaceIds: usedPlaceIdsIn(days) })
      : []

    return (
      <>
        <button
          type="button"
          onClick={() => setExpandedKey(isOpen ? null : key)}
          aria-expanded={isOpen}
          className={`w-full grid ${editable ? 'grid-cols-[20px_56px_1fr_auto] md:grid-cols-[20px_64px_1fr_auto]' : 'grid-cols-[56px_1fr_auto] md:grid-cols-[64px_1fr_auto]'} gap-4 py-3 text-left`}
        >
          {editable && (
            <DotsSixVertical size={16} className="no-print shrink-0 self-center text-ink-faint" aria-hidden="true" />
          )}
          <div className="font-utility font-bold text-[13.5px] md:text-[14px] text-ink-muted tabular">{stop.time}</div>
          <div className="flex flex-col gap-1 min-w-0">
            <div className="flex items-center justify-between gap-3 flex-wrap">
              <span className="font-bold text-[15px] flex items-center gap-1.5">
                {matched && <Sparkle size={13} weight="fill" className="text-chili shrink-0" aria-label={lang === 'vi' ? 'Hợp sở thích của bạn' : 'Matches your taste'} />}
                {place.name[lang]}
              </span>
              <span className={`font-utility text-[10.5px] font-bold uppercase tracking-wide px-2 py-[3px] rounded-full ${matched ? 'bg-herb text-herb-ink' : 'bg-paper-2 text-ink-muted'}`}>
                {stop.note[lang]}
              </span>
            </div>
            <div className="flex flex-wrap gap-4 text-[12.5px] text-ink-faint">
              <span className="flex items-center gap-1 text-herb font-medium">
                <CheckCircle size={13} /> {l.open(place.hours.close)}
              </span>
              <span className="flex items-center gap-1">
                <Ruler size={13} /> {stop.distance[lang]}
              </span>
              <span className="flex items-center gap-1 text-chili font-medium">
                <Wallet size={13} /> {priceRangeLabel(place.price, lang)}
              </span>
            </div>
          </div>
          <CaretDown size={15} className={`no-print shrink-0 self-center text-ink-faint transition-transform ${isOpen ? 'rotate-180' : ''}`} />
        </button>
        {isOpen && (
          <div className={`pb-4 flex flex-col gap-2 ${editable ? 'pl-[92px] md:pl-[100px]' : 'pl-[72px] md:pl-20'}`}>
            <div className="flex items-start gap-1.5 text-[13px] text-ink-muted">
              <MapPin size={14} className="text-chili shrink-0 mt-0.5" />
              <span><span className="text-ink-faint">{l.address}: </span>{place.address[lang]}</span>
            </div>
            <a
              href={mapsSearchUrl(place, lang)}
              target="_blank"
              rel="noreferrer"
              onClick={(e) => e.stopPropagation()}
              className="no-print font-utility text-[12.5px] font-semibold text-chili hover:underline self-start"
            >
              {l.viewOnMaps} ↗
            </a>
            {editable && (
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); setReplacingKey(isReplacing ? null : key) }}
                className="no-print inline-flex items-center gap-1.5 font-utility text-[12.5px] font-semibold text-ink-muted hover:text-chili transition-colors self-start"
              >
                <ArrowsClockwise size={14} /> {l.replaceStop}
              </button>
            )}
            {isReplacing && (
              <div className="no-print mt-1 rounded-lg border border-line-strong p-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="font-utility text-[11px] font-bold uppercase tracking-wide text-chili">{l.replacingTitle}</span>
                  <button type="button" onClick={(e) => { e.stopPropagation(); setReplacingKey(null) }} aria-label={l.cancel}>
                    <X size={14} className="text-ink-faint hover:text-chili transition-colors" />
                  </button>
                </div>
                {replaceStatus === 'replacing' ? (
                  <p className="text-[13px] text-ink-muted">{l.replacing}</p>
                ) : candidates.length === 0 ? (
                  <p className="text-[13px] text-ink-muted">{l.noCandidates}</p>
                ) : (
                  <div className="flex flex-col gap-1 max-h-[220px] overflow-y-auto">
                    {candidates.map((cand) => (
                      <button
                        key={cand.id}
                        type="button"
                        onClick={(e) => { e.stopPropagation(); handleReplace(dayIdx, i, cand) }}
                        className="flex items-center justify-between gap-2 rounded-md px-2.5 py-2 text-left hover:bg-paper-2 transition-colors"
                      >
                        <span className="text-[13px] font-medium truncate">{cand.name[lang]}</span>
                        <span className="font-utility text-[11px] text-chili shrink-0 tabular">
                          {(cand.liveRating ?? cand.rating)?.toFixed?.(1) ?? '–'}★
                        </span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </>
    )
  }

  return (
    <motion.div
      variants={fadeUp}
      initial="hidden"
      {...viewportProps}
      id="itinerary-ticket-print"
      className="w-full max-w-[880px] mx-auto grid grid-cols-1 md:grid-cols-[220px_1fr] bg-surface rounded-[14px] shadow-lifted relative"
    >
      <div className="p-6 flex flex-col gap-5 border-b md:border-b-0 md:border-r border-dashed border-line-strong relative">
        <span className="absolute w-[22px] h-[22px] rounded-full bg-paper -bottom-[11px] left-[-11px] md:top-[-11px] md:left-auto md:right-[-11px] md:bottom-auto" />
        <span className="absolute w-[22px] h-[22px] rounded-full bg-paper -bottom-[11px] right-[-11px] md:bottom-[-11px] md:left-auto md:right-[-11px] md:top-auto" />

        <StubItem icon={MapPin} k={l.destination} v={city.name[lang]} />
        <StubItem icon={Clock} k={l.duration} v={durationLabel} />
        <StubItem icon={Users} k={l.people} v={`${people} ${lang === 'vi' ? 'người' : people === 1 ? 'person' : 'people'}`} />
        <StubItem icon={TransportIcon} k={l.transport} v={TRANSPORT[transport][lang]} />
        <div className="flex flex-col gap-0.5">
          <span className="font-utility text-[10.5px] uppercase tracking-wider text-ink-faint">{l.budget}</span>
          <span className="font-bold text-[15px] tabular">{formatVnd(budget)}{l.perPerson}</span>
        </div>
        <Barcode />
      </div>

      <div className="p-6">
        <div className="flex items-baseline justify-between gap-3 mb-5 flex-wrap">
          <h3 className="font-display text-[22px] font-bold">{city.name[lang]}</h3>
          <span className="font-utility text-[10.5px] font-bold uppercase tracking-wide px-2.5 py-[3px] rounded-full bg-paper-2 text-ink-muted">
            {l.by}
          </span>
        </div>

        {days.map((day, dayIdx) => (
          <div key={dayIdx}>
            <div className="font-utility font-bold text-[12px] uppercase tracking-wide text-chili mt-6 mb-3 first:mt-0">
              {l.day(dayIdx + 1)}
            </div>
            {editable ? (
              <Reorder.Group as="div" axis="y" values={day} onReorder={(newOrder) => handleReorder(dayIdx, newOrder)}>
                {day.map((stop, i) => (
                  <Reorder.Item key={stop._uid ?? i} value={stop} as="div" className="border-t border-line first:border-t-0 cursor-grab active:cursor-grabbing bg-surface">
                    <StopRow stop={stop} dayIdx={dayIdx} i={i} />
                  </Reorder.Item>
                ))}
              </Reorder.Group>
            ) : (
              <motion.div variants={staggerContainer(0.06)} initial="hidden" {...viewportProps}>
                {day.map((stop, i) => (
                  <motion.div key={i} variants={fadeUp} className="border-t border-line first:border-t-0">
                    <StopRow stop={stop} dayIdx={dayIdx} i={i} />
                  </motion.div>
                ))}
              </motion.div>
            )}
          </div>
        ))}

        {hotels.length > 0 && (
          <div className="mt-6 pt-5 border-t border-dashed border-line-strong">
            <div className="font-utility font-bold text-[12px] uppercase tracking-wide text-chili mb-3">{l.hotelsTitle}</div>
            <div className="grid gap-3 sm:grid-cols-2">
              {[...hotels].sort((a, b) => (a.id === selectedHotelId ? -1 : b.id === selectedHotelId ? 1 : 0)).map((hotel) => {
                const isSelected = hotel.id === selectedHotelId
                return (
                <div key={hotel.id} className={`flex items-start gap-3 rounded-lg border px-3.5 py-3 ${isSelected ? 'border-chili bg-paper-2' : 'border-line-strong'}`}>
                  <Bed size={18} className="shrink-0 mt-0.5 text-herb" />
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold text-[13.5px] truncate">{hotel.name}</div>
                      {isSelected && (
                        <span className="shrink-0 font-utility text-[10px] font-bold uppercase tracking-wide px-2 py-[2px] rounded-full bg-chili text-chili-ink">
                          {l.hotelSelected}
                        </span>
                      )}
                    </div>
                    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mt-1 font-utility text-[11.5px] text-ink-faint">
                      {hotel.rating != null && (
                        <span className="flex items-center gap-1 text-chili font-medium">
                          <Star size={12} weight="fill" /> {hotel.rating.toFixed(1)}
                          {hotel.userRatingCount ? ` · ${l.hotelReviews(hotel.userRatingCount)}` : ''}
                        </span>
                      )}
                      {hotel.priceLevel && PRICE_LEVEL_LABEL[hotel.priceLevel] && (
                        <span>{PRICE_LEVEL_LABEL[hotel.priceLevel][lang]}</span>
                      )}
                    </div>
                    <div className="no-print flex items-center gap-3 mt-2.5">
                      <Link
                        to={`/booking/${hotel.id}`}
                        state={{ hotel }}
                        className="font-utility text-[12px] font-semibold text-chili-ink bg-chili px-3 py-1.5 rounded-full hover:shadow-soft transition-shadow"
                      >
                        {l.bookRoom}
                      </Link>
                      <a
                        href={hotelMapsUrl(hotel)}
                        target="_blank"
                        rel="noreferrer"
                        aria-label={l.viewOnMaps}
                        className="text-ink-faint hover:text-chili transition-colors"
                      >
                        <ArrowSquareOut size={16} />
                      </a>
                    </div>
                  </div>
                </div>
                )
              })}
            </div>
          </div>
        )}
      </div>
    </motion.div>
  )
}

function StubItem({ icon: Icon, k, v }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="font-utility text-[10.5px] uppercase tracking-wider text-ink-faint">{k}</span>
      <span className="font-bold text-[15px] flex items-center gap-1.5">
        <Icon size={16} className="text-herb" weight="bold" />
        {v}
      </span>
    </div>
  )
}

function Barcode() {
  let seed = 1234567
  const rnd = () => {
    seed = (seed * 9301 + 49297) % 233280
    return seed / 233280
  }
  const bars = Array.from({ length: 26 }, () => 30 + rnd() * 70)
  return (
    <div className="flex gap-[3px] h-[34px] items-end mt-auto" aria-hidden="true">
      {bars.map((h, i) => (
        <i key={i} className="bg-ink opacity-55 w-[3px] block" style={{ height: `${h}%` }} />
      ))}
    </div>
  )
}
