-- Write-through cache for places discovered live via Google Places when a
-- user plans a trip to a destination outside the curated city list. Without
-- this, those places only ever lived in an in-memory JS registry
-- (src/data/destinations.js) and vanished on every page refresh, breaking
-- deep links (/place/:id) and any saved itinerary referencing them.
-- Public read/insert: this is non-sensitive third-party data (Google Places
-- results), the same trust level as video_reviews, not personal data.
create table if not exists public.custom_places (
  id text primary key,
  data jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.custom_places enable row level security;

create policy "custom_places_public_select" on public.custom_places
  for select using (true);

create policy "custom_places_public_insert" on public.custom_places
  for insert with check (true);

create policy "custom_places_public_update" on public.custom_places
  for update using (true) with check (true);

-- Saved trip plans generated by the /plan AI planner. Owner-only, so a
-- logged-in user can revisit an itinerary later or from another device
-- instead of losing it the moment they navigate away or refresh.
create table if not exists public.itineraries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  city_id text,
  custom_city_name text,
  duration int not null,
  budget bigint not null,
  people int not null,
  transport text not null,
  prefs jsonb not null default '[]',
  days jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists itineraries_user_id_idx on public.itineraries (user_id);

alter table public.itineraries enable row level security;

create policy "itineraries_owner_select" on public.itineraries
  for select using (auth.uid() = user_id);

create policy "itineraries_owner_insert" on public.itineraries
  for insert with check (auth.uid() = user_id);

create policy "itineraries_owner_delete" on public.itineraries
  for delete using (auth.uid() = user_id);
